### ISSUE TITLE
Complete Figma Wireframe

### ISSUE THREAD

**Issue by didierganthier** [Vizyone/Spotlight#4]
Figma https://www.figma.com/proto/o6oHJX8blt3DEfXCuj1W3X/Spotlight?node-id=143%3A1&scaling=scale-down
- [x] Connect different Figma screens with actions
- [x] Represent drawer navigation in figma
- [x] Submit final Wireframe

**Comment by amiralda** [comment]
The QR code and the email validation was not for the MVP version
